//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTI_Editor.WWW
{
    public partial class QuestionEditor
    {
        protected global::System.Web.UI.WebControls.Button       btnBack;
        protected global::System.Web.UI.WebControls.Label        lblError;
        protected global::System.Web.UI.WebControls.Label        lblQuestionType;
        protected global::System.Web.UI.WebControls.TextBox      txtTitle;
        protected global::System.Web.UI.WebControls.DropDownList  ddlType;
        protected global::System.Web.UI.WebControls.TextBox      txtQuestionText;
        protected global::System.Web.UI.WebControls.Panel        pnlChoices;
        protected global::System.Web.UI.WebControls.Repeater     choiceRepeater;
        protected global::System.Web.UI.WebControls.Button       btnAddAnswer;
        protected global::System.Web.UI.WebControls.Panel        pnlShortAnswer;
        protected global::System.Web.UI.WebControls.TextBox      txtShortAnswer;
        protected global::System.Web.UI.WebControls.Panel        pnlRange;
        protected global::System.Web.UI.WebControls.TextBox      txtRangeMin;
        protected global::System.Web.UI.WebControls.TextBox      txtRangeMax;
        protected global::System.Web.UI.WebControls.Button       btnDeleteQuestion;
        protected global::System.Web.UI.WebControls.Button       btnDiscard;
        protected global::System.Web.UI.WebControls.Button       btnSave;
    }
}
