//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTI_Editor.WWW
{
    public partial class QuizOverview
    {
        protected global::System.Web.UI.WebControls.Button       exZipButton;
        protected global::System.Web.UI.WebControls.TextBox      txtQuizTitle;
        protected global::System.Web.UI.WebControls.Label        lblOverviewError;
        protected global::System.Web.UI.WebControls.Repeater     questionList;
        protected global::System.Web.UI.WebControls.TextBox      txtNewQuestionTitle;
        protected global::System.Web.UI.WebControls.DropDownList  ddlNewQuestionType;
        protected global::System.Web.UI.WebControls.Button       btnAddQuestion;
        protected global::System.Web.UI.WebControls.Label        lblAddError;
    }
}
